name: Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: "Install dependencies"
      run: sudo apt-get install -y g++-9 make liblapack-dev libblas-dev libgsl-dev libomp-dev lcov
    - name: setup
      run: cp ./doc/examples/Makefile ./ && chmod +x ./src/tests/lcov.sh 
    - name: Build ampsci & use LCOV to prepare report
      run: ./src/tests/lcov.sh
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2