name: Tests

on:
  push:
    branches:
      - main

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: "Install dependencies"
      run: sudo apt install g++-11 make liblapack-dev libblas-dev libgsl-dev libomp-dev
    - name: setup
      run: cp ./doc/Makefile.example ./Makefile
    - name: Build ampsci (g++, dev mode, with Werror)
      run: make CXX='g++-11 -Werror' Build=dev tests
    - name: Run (quick) unit+regression tests
      run: ./tests ~[Slow]
